import { useEffect, useState } from 'react'
import { confirmarRecebimentoPix, atualizarStatusPedido, listarPedidos, prazoEntregaPedido } from '../services/pedidosService'
import { enviarImagemProduto, listarProdutos, removerProduto, salvarProduto } from '../services/produtosService'
import { listarClientes } from '../services/usuariosService'
import { listarDocesProntaEntrega, removerDoceProntaEntrega, salvarDoceProntaEntrega } from '../services/docesProntaEntregaService'
import AdminGaleriaBolos from '../components/AdminGaleriaBolos'
import AdminAvaliacoes from '../components/AdminAvaliacoes'
import './Admin.css'
import './AdminProdutos.css'

const etapas = [['novo', 'Novos'], ['producao', 'Em produção'], ['pronto', 'Prontos'], ['entregue', 'Finalizados']]
const produtoVazio = { nome: '', categoria: 'Bolos', preco: '', descricao: '', imagem: '', disponivel: true }

export default function Admin() {
  const [confirmandoPix, setConfirmandoPix] = useState(null)
  const [aba, setAba] = useState('Visão geral'); const [pedidos, setPedidos] = useState([]); const [produtos, setProdutos] = useState([]); const [clientes, setClientes] = useState([]); const [doces, setDoces] = useState([]); const [produtoEditado, setProdutoEditado] = useState(null); const [erro, setErro] = useState(''); const [agora, setAgora] = useState(Date.now()); const [pedidoArrastado, setPedidoArrastado] = useState(null); const [colunaDestino, setColunaDestino] = useState(null); const [salvandoImagem, setSalvandoImagem] = useState(false); const [confirmacaoExclusao, setConfirmacaoExclusao] = useState(null); const [excluindo, setExcluindo] = useState(false)
  useEffect(() => { Promise.allSettled([listarPedidos(), listarProdutos(true), listarClientes(), listarDocesProntaEntrega(true)]).then(([pedidosResult, produtosResult, clientesResult, docesResult]) => { if (pedidosResult.status === 'fulfilled') setPedidos(pedidosResult.value); else setErro('Não foi possível atualizar os pedidos agora. Verifique sua conexão e tente novamente.'); if (produtosResult.status === 'fulfilled') setProdutos(produtosResult.value); if (clientesResult.status === 'fulfilled') setClientes(clientesResult.value); if (docesResult.status === 'fulfilled') setDoces(docesResult.value) }) }, [])
  useEffect(() => { const intervalo = window.setInterval(() => setAgora(Date.now()), 1000); return () => window.clearInterval(intervalo) }, [])
  useEffect(() => { const soltarPedido = () => { if (pedidoArrastado && colunaDestino) trocarStatus(pedidoArrastado, colunaDestino); setPedidoArrastado(null); setColunaDestino(null) }; window.addEventListener('pointerup', soltarPedido); return () => window.removeEventListener('pointerup', soltarPedido) }, [pedidoArrastado, colunaDestino])
  const total = (status) => pedidos.filter((p) => p.status === status).length; const faturamento = pedidos.reduce((s, p) => s + Number(p.valor_total || 0), 0)
  async function confirmarPix(id) {
    if (!window.confirm('Você conferiu no banco o recebimento do Pix deste pedido?')) return
    setConfirmandoPix(id); setErro('')
    try { const atualizado = await confirmarRecebimentoPix(id); setPedidos((lista) => lista.map((p) => p.id === id ? { ...p, ...atualizado } : p)) }
    catch (e) { setErro(e.message) }
    finally { setConfirmandoPix(null) }
  }
  async function trocarStatus(id, status) { try { await atualizarStatusPedido(id, status); setPedidos((itens) => itens.map((p) => p.id === id ? { ...p, status } : p)) } catch (e) { setErro(e.message) } }
  async function excluir(item, tipo = 'produto') { setExcluindo(true); try { if (tipo === 'doce') { await removerDoceProntaEntrega(item.id); setDoces((itens) => itens.filter((d) => d.id !== item.id)) } else { await removerProduto(item.id); setProdutos((itens) => itens.filter((p) => p.id !== item.id)) } } catch (e) { setErro(e.message) } finally { setExcluindo(false); setConfirmacaoExclusao(null) } }
  async function salvar(event) { event.preventDefault(); const dados = Object.fromEntries(new FormData(event.currentTarget)); const arquivo = dados.imagem_arquivo; delete dados.imagem_arquivo; setErro(''); setSalvandoImagem(true); try { const imagem = arquivo?.size ? await enviarImagemProduto(arquivo) : produtoEditado.imagem; const produto = { ...produtoEditado, ...dados, imagem, preco: Number(dados.preco), disponivel: dados.disponivel === 'on' }; const salvo = await salvarProduto(produto); setProdutos((itens) => produto.id ? itens.map((p) => p.id === salvo.id ? salvo : p) : [...itens, salvo]); setProdutoEditado(null) } catch (e) { setErro(e.message) } finally { setSalvandoImagem(false) } }
  async function alternarDisponibilidade(produto) { try { const salvo = await salvarProduto({ ...produto, disponivel: !produto.disponivel }); setProdutos((itens) => itens.map((p) => p.id === salvo.id ? salvo : p)) } catch (e) { setErro(e.message) } }
  async function salvarDoce(event) { event.preventDefault(); const dados = Object.fromEntries(new FormData(event.currentTarget)); const arquivo = dados.imagem_arquivo; delete dados.imagem_arquivo; const { tipo, categoria, ...doceBase } = produtoEditado; setErro(''); setSalvandoImagem(true); try { const imagem = arquivo?.size ? await enviarImagemProduto(arquivo) : doceBase.imagem; const doce = { ...doceBase, ...dados, imagem, preco: Number(dados.preco), quantidade_disponivel: Number(dados.quantidade_disponivel), disponivel: dados.disponivel === 'on' }; const salvo = await salvarDoceProntaEntrega(doce); setDoces((itens) => doce.id ? itens.map((d) => d.id === salvo.id ? salvo : d) : [...itens, salvo]); setProdutoEditado(null) } catch (e) { setErro(e.message) } finally { setSalvandoImagem(false) } }
  return <div className="admin"><aside><a href="#inicio">♥ Bolos <i>da Lu</i></a><small>PAINEL ADMINISTRATIVO</small>{['Visão geral', 'Pedidos', 'Produtos', 'Pronta entrega', 'Galeria de bolos', 'Avalia\u00e7\u00f5es', 'Clientes', 'Relatórios'].map((nome) => <button className={aba === nome ? 'ativo' : ''} onClick={() => setAba(nome)} key={nome}>{nome}</button>)}</aside><section><header><div><small>Olá, Lu! ✦</small><h1>{aba}</h1></div><a href="#inicio">Ver loja ↗</a></header>{erro && <p className="erro">{erro}</p>}
    {aba === 'Visão geral' && <><div className="metricas"><Card valor={total('novo')} texto="NOVOS" /><Card valor={total('producao')} texto="PRODUÇÃO" /><Card valor={total('pronto')} texto="PRONTOS" /><Card valor={`R$ ${faturamento.toFixed(2)}`} texto="FATURAMENTO" /></div><h2>Pedidos recentes</h2><Lista pedidos={pedidos.slice(0, 5)} /></>}
    {aba === 'Pedidos' && <><p className="dica-arrastar">⋮⋮ Segure a alça pontilhada e solte o pedido na coluna desejada.</p><div className="quadro">{etapas.map(([status, titulo]) => <div className={`coluna ${colunaDestino === status ? 'coluna-destino' : ''}`} key={status} onPointerEnter={() => { if (pedidoArrastado) setColunaDestino(status) }} onPointerLeave={() => { if (pedidoArrastado && colunaDestino === status) setColunaDestino(null) }}><h2>{titulo} <span>{total(status)}</span></h2>{pedidos.filter((p) => p.status === status).map((p) => { const prazo = prazoEntregaPedido(p.criado_em); return <article className={pedidoArrastado === p.id ? 'arrastando' : ''} key={p.id}><span className="alca-arraste" onPointerDown={(e) => { e.preventDefault(); setPedidoArrastado(p.id); setColunaDestino(null) }} title="Arrastar pedido" aria-label="Arrastar pedido">⋮⋮</span><b>#{p.id} · {p.usuarios?.nome || 'Cliente'}</b><small>{p.itens_pedido?.[0]?.nome_produto || p.itens_pedido?.[0]?.produtos?.nome || 'Encomenda personalizada'}</small><small>Feito: {prazo.realizado}</small>{p.endereco?.includes('agendada:') ? <small>{p.endereco}</small> : <small>Entrega: {prazo.estimativa}</small>}<small>Pagamento: {p.forma_pagamento || 'Não informado'}{p.forma_pagamento === 'Pix' && (p.pagamento_confirmado_em ? ' · Recebido' : ' · Pendente')}</small>{p.forma_pagamento === 'Pix' && !p.pagamento_confirmado_em && <button className="confirmar-pix-admin" disabled={confirmandoPix !== null} onClick={() => confirmarPix(p.id)}>{confirmandoPix === p.id ? 'Confirmando...' : 'Confirmar recebimento do Pix'}</button>}{!p.endereco?.includes('agendada:') && <ContagemRegressiva fim={prazo.fim} agora={agora} status={p.status}/>}<select value={p.status} onChange={(e) => trocarStatus(p.id, e.target.value)}>{etapas.map(([v, n]) => <option value={v} key={v}>{n}</option>)}</select></article> })}</div>)}</div></>}
    {aba === 'Produtos' && <><button className="adicionar" onClick={() => setProdutoEditado(produtoVazio)}>+ Cadastrar produto</button><div className="lista-admin produtos-admin">{produtos.map((p) => <article key={p.id}>{p.imagem ? <img src={p.imagem} alt={p.nome} /> : <div className="sem-imagem">🍰</div>}<div className="dados-produto"><b>{p.nome}</b><small>{p.categoria} · R$ {Number(p.preco).toFixed(2)}</small><small>{p.descricao || 'Sem descrição'}</small></div><div className="acoes-produto"><label className="switch"><input type="checkbox" checked={p.disponivel} onChange={() => alternarDisponibilidade(p)} /><span /></label><small>{p.disponivel ? 'Ativo' : 'Inativo'}</small><button onClick={() => setProdutoEditado(p)}>Editar</button><button onClick={() => setConfirmacaoExclusao({ item: p, tipo: 'produto' })}>Excluir</button></div></article>)}</div></>}
    {aba === 'Pronta entrega' && <><button className="adicionar" onClick={() => setProdutoEditado({ ...produtoVazio, quantidade_disponivel: 1, tipo: 'doce' })}>+ Adicionar doce</button><div className="lista-admin produtos-admin">{doces.map((d) => <article key={d.id}>{d.imagem ? <img src={d.imagem} alt={d.nome} /> : <div className="sem-imagem">🧁</div>}<div className="dados-produto"><b>{d.nome}</b><small>R$ {Number(d.preco).toFixed(2)} · {d.quantidade_disponivel} em estoque</small><small>{d.descricao || 'Sem descrição'}</small></div><div className="acoes-produto"><button onClick={() => setProdutoEditado({ ...d, tipo: 'doce' })}>Editar</button><button onClick={() => setConfirmacaoExclusao({ item: d, tipo: 'doce' })}>Excluir</button></div></article>)}</div></>}
    {aba === 'Galeria de bolos' && <AdminGaleriaBolos />}
    {aba === 'Avalia\u00e7\u00f5es' && <AdminAvaliacoes />}
    {aba === 'Clientes' && <div className="lista-admin">{clientes.map((c) => <article key={c.id}><div><b>{c.nome}</b><small>{c.email} · {c.telefone || 'Sem telefone'}</small></div></article>)}</div>}
    {aba === 'Relatórios' && <div className="metricas"><Card valor={pedidos.length} texto="PEDIDOS REALIZADOS" /><Card valor={`R$ ${faturamento.toFixed(2)}`} texto="FATURAMENTO" /><Card valor={`R$ ${pedidos.length ? (faturamento / pedidos.length).toFixed(2) : '0,00'}`} texto="TICKET MÉDIO" /></div>}
  </section>{produtoEditado && <ModalProduto produto={produtoEditado} aoFechar={() => setProdutoEditado(null)} aoSalvar={produtoEditado.tipo === 'doce' ? salvarDoce : salvar} salvando={salvandoImagem} erro={erro} />}{confirmacaoExclusao && <div className="admin-confirmacao-fundo" role="presentation" onMouseDown={() => { if (!excluindo) setConfirmacaoExclusao(null) }}><section className="admin-confirmacao" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><span className="admin-confirmacao-icone" aria-hidden="true">!</span><h2>Excluir {confirmacaoExclusao.tipo === 'doce' ? 'doce' : 'produto'}?</h2><p><strong>{confirmacaoExclusao.item.nome}</strong> será removido do catálogo.</p><div><button type="button" disabled={excluindo} onClick={() => setConfirmacaoExclusao(null)}>Cancelar</button><button type="button" className="confirmar" disabled={excluindo} onClick={() => excluir(confirmacaoExclusao.item, confirmacaoExclusao.tipo)}>{excluindo ? 'Excluindo...' : 'Excluir'}</button></div></section></div>}</div>
}
function ModalProduto({ produto, aoFechar, aoSalvar, salvando, erro }) { const doce = produto.tipo === 'doce'; const [previa, setPrevia] = useState(produto.imagem || ''); return <div className="produto-modal"><form className="produto-form" onSubmit={aoSalvar}><button className="fechar-produto" type="button" onClick={aoFechar}>×</button><p className="sobretitulo">{doce ? 'pronta entrega' : 'catálogo'}</p><h2>{produto.id ? 'Editar produto' : doce ? 'Adicionar doce' : 'Cadastrar produto'}</h2>{erro && <p className="erro-upload-produto">{erro.includes('Bucket not found') ? 'O armazenamento de imagens ainda não foi configurado. Execute o arquivo SQL de migração no Supabase.' : erro}</p>}<div className="campos-produto"><label>Nome do produto<input name="nome" defaultValue={produto.nome} required /></label>{!doce && <label>Tipo / categoria<select name="categoria" defaultValue={produto.categoria}><option>Bolos</option><option>Docinhos</option><option>Kits</option><option>Copos e doces</option></select></label>}<label>Preço (R$)<input name="preco" type="number" min="0" step="0.01" defaultValue={produto.preco} required /></label>{doce && <label>Quantidade disponível<input name="quantidade_disponivel" type="number" min="0" defaultValue={produto.quantidade_disponivel} required /></label>}<label className={!doce ? '' : 'campo-total imagem-upload-produto'}>Imagem do produto<input name="imagem_arquivo" type="file" accept="image/jpeg,image/png,image/webp" onChange={(evento) => { const arquivo = evento.target.files?.[0]; if (arquivo) setPrevia(URL.createObjectURL(arquivo)) }} /><span>Escolha uma foto do computador (JPG ou JPEG, PNG ou WEBP, até 5 MB).</span>{previa && <img src={previa} alt="Prévia da imagem do produto" />}</label><label className="campo-total">Descrição<textarea name="descricao" defaultValue={produto.descricao || ''} rows="4" required /></label><label className="disponivel"><input name="disponivel" type="checkbox" defaultChecked={produto.disponivel} /> Disponível para venda</label></div><div className="botoes-form"><button type="button" onClick={aoFechar} disabled={salvando}>Cancelar</button><button type="submit" disabled={salvando}>{salvando ? 'Enviando imagem...' : 'Salvar produto →'}</button></div></form></div> }
function Card({ valor, texto }) { return <article><b>{valor}</b><span>{texto}</span></article> }
function ContagemRegressiva({ fim, agora, status }) { if (status === 'entregue' || status === 'cancelado') return <span className="tempo-pedido finalizado">Pedido finalizado</span>; const diferenca = fim.getTime() - agora; const atrasado = diferenca < 0; const totalSegundos = Math.floor(Math.abs(diferenca) / 1000); const horas = Math.floor(totalSegundos / 3600); const minutos = Math.floor((totalSegundos % 3600) / 60); const segundos = totalSegundos % 60; const tempo = `${horas ? `${horas}h ` : ''}${String(minutos).padStart(2, '0')}m ${String(segundos).padStart(2, '0')}s`; return <span className={`tempo-pedido ${atrasado ? 'atrasado' : 'no-prazo'}`}>{atrasado ? `Atrasado há ${tempo}` : `Restam ${tempo}`}</span> }
function Lista({ pedidos }) { return <div className="lista-admin">{pedidos.map((p) => { const prazo = prazoEntregaPedido(p.criado_em); return <article key={p.id}><div><b>#{p.id} · {p.usuarios?.nome || 'Cliente'}</b><small>{p.status} · pedido feito: {prazo.realizado}</small><small>Pagamento: {p.forma_pagamento || 'Não informado'}</small><small>Estimativa: {prazo.estimativa}</small></div><b>R$ {Number(p.valor_total).toFixed(2)}</b></article> })}</div> }
