import { useEffect, useState } from 'react'
import { listarAvaliacoesAdmin, removerAvaliacao } from '../services/avaliacoesAdminService'

export default function AdminAvaliacoes() {
  const [itens, setItens] = useState([]); const [carregando, setCarregando] = useState(true); const [erro, setErro] = useState(''); const [removendo, setRemovendo] = useState(null); const [confirmacao, setConfirmacao] = useState(null)
  async function carregar() { setCarregando(true); setErro(''); try { setItens(await listarAvaliacoesAdmin()) } catch (error) { setErro(error.message) } finally { setCarregando(false) } }
  useEffect(() => { carregar() }, [])
  async function excluir(item) { setRemovendo(item.id); setErro(''); try { const aviso = await removerAvaliacao(item); setItens((lista) => lista.filter((avaliacao) => avaliacao.id !== item.id)); if (aviso) setErro(aviso) } catch (error) { setErro(error.message) } finally { setRemovendo(null); setConfirmacao(null) } }
  if (carregando) return <p>Carregando avaliações...</p>
  return <><div className="lista-admin avaliacoes-admin">{erro && <p className="erro">{erro}</p>}{!itens.length && <p>Nenhuma avaliação publicada.</p>}{itens.map((item) => <article key={item.id}>{item.imagem && <img src={item.imagem} alt="Foto enviada na avaliação" />}<div><b>{item.nome}</b><small className="estrelas-admin">{'★'.repeat(item.nota)}{'☆'.repeat(5 - item.nota)}</small><p>{item.comentario}</p><small>{new Date(item.criado_em).toLocaleDateString('pt-BR')}</small></div><button disabled={removendo === item.id} onClick={() => setConfirmacao(item)}>{removendo === item.id ? 'Excluindo...' : 'Excluir'}</button></article>)}</div>{confirmacao && <div className="admin-confirmacao-fundo" role="presentation" onMouseDown={() => { if (!removendo) setConfirmacao(null) }}><section className="admin-confirmacao" role="dialog" aria-modal="true" aria-labelledby="admin-confirmacao-titulo" onMouseDown={(event) => event.stopPropagation()}><span className="admin-confirmacao-icone" aria-hidden="true">!</span><h2 id="admin-confirmacao-titulo">Excluir avaliação?</h2><p>A avaliação de <strong>{confirmacao.nome}</strong> será removida do site. Essa ação não pode ser desfeita.</p><div><button type="button" disabled={Boolean(removendo)} onClick={() => setConfirmacao(null)}>Cancelar</button><button type="button" className="confirmar" disabled={Boolean(removendo)} onClick={() => excluir(confirmacao)}>{removendo ? 'Excluindo...' : 'Excluir avaliação'}</button></div></section></div>}</>
}
